In [2]:
import io, sys
import pandas as pd
import json

In [3]:
langs = ["danish", "english", "french", "persian", "spanish", "vietnamese"]

In [4]:
danishDFTrain = pd.read_json("../data/"+langs[0]+"/train.json")
danishDFDev = pd.read_json("../data/"+langs[0]+"/dev.json")

englishDFTrainLegal = pd.read_json("../data/"+langs[1]+"/legal/train.json")
englishDFDevLegal = pd.read_json("../data/"+langs[1]+"/legal/dev.json")
englishDFTrainScientific = pd.read_json("../data/"+langs[1]+"/scientific/train.json")
englishDFDevScientific = pd.read_json("../data/"+langs[1]+"/scientific/dev.json")

frenchDFTrain = pd.read_json("../data/"+langs[2]+"/train.json")
frenchDFDev = pd.read_json("../data/"+langs[2]+"/dev.json")

persianDFTrain = pd.read_json("../data/"+langs[3]+"/train.json")
persianDFDev = pd.read_json("../data/"+langs[3]+"/dev.json")

spanishDFTrain = pd.read_json("../data/"+langs[4]+"/train.json")
spanishDFDev = pd.read_json("../data/"+langs[4]+"/dev.json")

vietnameseDFTrain = pd.read_json("../data/"+langs[5]+"/train.json")
vietnameseDFDev = pd.read_json("../data/"+langs[5]+"/dev.json")

In [5]:
danishDFTrainResults = pd.read_json("../results/baseline/danishtrain.json")
danishDFDevResults = pd.read_json("../results/baseline/danishdev.json")

englishDFTrainLegalResults = pd.read_json("../results/baseline/englishlegaltrain.json")
englishDFDevLegalResults = pd.read_json("../results/baseline/englishlegaldev.json")
englishDFTrainScientificResults = pd.read_json("../results/baseline/englishscientifictrain.json")
englishDFDevScientificResults = pd.read_json("../results/baseline/englishscientificdev.json")

frenchDFTrainResults = pd.read_json("../results/baseline/frenchtrain.json")
frenchDFDevResults = pd.read_json("../results/baseline/frenchdev.json")

persianDFTrainResults = pd.read_json("../results/baseline/persiantrain.json")
persianDFDevResults = pd.read_json("../results/baseline/persiandev.json")

spanishDFTrainResults = pd.read_json("../results/baseline/spanishtrain.json")
spanishDFDevResults = pd.read_json("../results/baseline/spanishdev.json")

vietnameseDFTrainResults = pd.read_json("../results/baseline/vietnamesetrain.json")
vietnameseDFDevResults = pd.read_json("../results/baseline/vietnamesedev.json")

In [6]:
englishDFTrainScientificResults

        ID                                           acronyms    long-forms
0        1                                                 []            []
1        2                                                 []            []
2        3                                                 []            []
3        4                                         [[27, 36]]    [[98, 26]]
4        5                                                 []            []
...    ...                                                ...           ...
3975  3976                                                 []            []
3976  3977                               [[22, 25], [26, 32]]    [[90, 25]]
3977  3978                                           [[0, 5]]  [[127, 142]]
3978  3979  [[0, 7], [19, 22], [23, 25], [46, 52], [56, 65...  [[145, 175]]
3979  3980                                       [[110, 114]]            []

[3980 rows x 3 columns]

In [7]:
englishDFTrainScientific

,text,acronyms,long-forms,ID
0,92\]. This selective approach led to significa...,"[[91, 98]]","[[77, 89]]",1
1,We conduct a case study of dialectal language ...,"[[119, 122]]","[[93, 117]]",2
2,An arguably better approach to representation...,"[[91, 94]]","[[59, 89]]",3
3,"23-28, 1992 Proceedings of NAACL-HLT 2015 St...","[[71, 74], [29, 38]]","[[44, 69]]",4
4,"itly mark objects of prepositions (POBJ), poss...","[[119, 121], [35, 39], [76, 81], [95, 99], [16...","[[105, 117], [10, 33], [56, 74], [84, 93], [15...",5
...,...,...,...,...
3975,take et al (2005)) for the representation of m...,"[[112, 115], [55, 61]]","[[82, 110]]",3976
3976,clickthrough data. In ACM SIGKDD Conference on...,"[[84, 87], [22, 25], [26, 32]]","[[47, 75]]",3977
3977,S2LS. The best parameters were then used on th...,"[[88, 92], [0, 4]]","[[48, 86]]",3978
3978,C-NOUN: Nouns with POS NN that are not marked ...,"[[89, 92], [0, 6], [19, 22], [23, 25], [46, 52...","[[67, 81]]",3979
3979,"text corpus, to be made available without roya...","[[111, 115]]","[[121, 157]]",3980

In [8]:
danishDFTrainResults['text'] = danishDFTrain['text']
danishDFDevResults['text'] = danishDFDev['text']
englishDFTrainLegalResults['text'] = englishDFTrainLegal['text']
englishDFDevLegalResults['text'] = englishDFDevLegal['text']
englishDFTrainScientificResults['text'] = englishDFTrainScientific['text']
englishDFDevScientificResults['text'] = englishDFDevScientific['text']
frenchDFTrainResults['text'] = frenchDFTrain['text']
frenchDFDevResults['text'] = frenchDFDev['text']
persianDFTrainResults['text'] = persianDFTrain['text']
persianDFDevResults['text'] = persianDFDev['text']
spanishDFTrainResults['text'] = spanishDFTrain['text']
spanishDFDevResults['text'] = spanishDFDev['text']
vietnameseDFTrainResults['text'] = vietnameseDFTrain['text']
vietnameseDFDevResults['text'] = vietnameseDFDev['text']

In [9]:
englishDFTrainScientificResults

,ID,acronyms,long-forms,text
0,1,[],[],92\]. This selective approach led to significa...
1,2,[],[],We conduct a case study of dialectal language ...
2,3,[],[],An arguably better approach to representation...
3,4,"[[27, 36]]","[[98, 26]]","23-28, 1992 Proceedings of NAACL-HLT 2015 St..."
4,5,[],[],"itly mark objects of prepositions (POBJ), poss..."
...,...,...,...,...
3975,3976,[],[],take et al (2005)) for the representation of m...
3976,3977,"[[22, 25], [26, 32]]","[[90, 25]]",clickthrough data. In ACM SIGKDD Conference on...
3977,3978,"[[0, 5]]","[[127, 142]]",S2LS. The best parameters were then used on th...
3978,3979,"[[0, 7], [19, 22], [23, 25], [46, 52], [56, 65...","[[145, 175]]",C-NOUN: Nouns with POS NN that are not marked ...
3979,3980,"[[110, 114]]",[],"text corpus, to be made available without roya..."

In [10]:
# AUTHOR: Hadeel S

def create_acronyms(data):
    acs2 = []
    longf = []

    acros = data.acronyms.values
    txt = data.text.values
    zipped = list(zip(txt,acros))
    for z in zipped:
        acs = []
        for i in range(len(z[1])):
            acs.append(z[0][z[1][i][0]:z[1][i][1]])
        acs2.append(acs)
    data['acronyms-text'] =acs2
    
# Creating long forms from here

    longform = data["long-forms"].values
    zipped2 = list(zip(txt,longform))
    for z2 in zipped2:
        longform_temp = []
        for i in range(len(z2[1])):
            longform_temp.append(z2[0][z2[1][i][0]:z2[1][i][1]])
        longf.append(longform_temp)
    data["long-forms-text"]= longf
    
    return data

In [11]:
englishDFTrainScientificResults = create_acronyms(englishDFTrainScientificResults)
englishDFDevScientificResults = create_acronyms(englishDFDevScientificResults)
englishDFTrainLegalResults = create_acronyms(englishDFTrainLegalResults)
englishDFDevLegalResults = create_acronyms(englishDFDevLegalResults)
danishDFTrainResults = create_acronyms(danishDFTrainResults)
danishDFDevResults = create_acronyms(danishDFDevResults)
frenchDFTrainResults = create_acronyms(frenchDFTrainResults)
frenchDFDevResults = create_acronyms(frenchDFDevResults)
persianDFTrainResults = create_acronyms(persianDFTrainResults)
persianDFDevResults = create_acronyms(persianDFDevResults)
spanishDFTrainResults = create_acronyms(spanishDFTrainResults)
spanishDFDevResults = create_acronyms(spanishDFDevResults)
vietnameseDFTrainResults = create_acronyms(vietnameseDFTrainResults)
vietnameseDFDevResults = create_acronyms(vietnameseDFDevResults)

In [12]:
englishDFDevScientificResults['long-forms-text']

0      []
1      []
2      []
3      []
4      []
       ..
492    []
493    []
494    []
495    []
496    []
Name: long-forms-text, Length: 497, dtype: object